---
version: "2"

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/uk-pdc/metadata-infrastructure/metadata-generator:latest
    command: flask run --host 0.0.0.0 --port 9000
    volumes:
      - .:/usr/src/app
    ports:
      - 9000:9000
