---
version: "2"

services:
  terraform:
    image: hashicorp/terraform:0.11.8
    working_dir: /usr/src/app/provisioning/terraform
    entrypoint: ash
    volumes:
      - .:/usr/src/app/provisioning/terraform
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
